on:
  push:
    branches:
      - main
    paths:
      - 'django-todo/**'
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r django-todo/requirements.txt

      - name: Run tests
        run: |
          cd django-todo
          python manage.py test
      - name: Build and run Docker Compose
        run: |
          cd django-todo
          docker-compose up -d --build